branch-defaults:
  master:
    environment: wensTest-env
global:
  application_name: Wen's Test
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-east-1
  profile: null
  sc: git
